apiVersion: v1
kind: Namespace
metadata:
  name: gphotos-sync
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gphotos-sync-short
  namespace: gphotos-sync
spec:
  schedule: "50 */3 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          hostPID: true
          containers:
          - name: gphotos-sync
            image: ghcr.io/iaguis/gphotos-cdp:v1
            imagePullPolicy: Always
            command:
            - /usr/bin/gphotos-sync.sh
            - short
            env:
            - name: HEALTHCHECK_ID
              valueFrom:
                secretKeyRef:
                  name: gphotos-sync-short-healthcheck
                  key: id
            volumeMounts:
            - mountPath: /tmp/gphotos-cdp
              name: chrome-profile
            - mountPath: /home/nonroot/Downloads/gphotos-cdp
              name: google-photos
          volumes:
          - name: chrome-profile
            hostPath:
              path: /mnt/locke-nas/iago-home/gphotos-cdp
              type: Directory
          - name: google-photos
            hostPath:
              path: /mnt/locke-nas/google-photos
              type: Directory
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gphotos-sync-medium
  namespace: gphotos-sync
spec:
  schedule: "0 0 * * 6"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          hostPID: true
          containers:
          - name: gphotos-sync
            image: ghcr.io/iaguis/gphotos-cdp:v1
            imagePullPolicy: Always
            command:
            - /usr/bin/gphotos-sync.sh
            - medium
            env:
            - name: HEALTHCHECK_ID
              valueFrom:
                secretKeyRef:
                  name: gphotos-sync-medium-healthcheck
                  key: id
            volumeMounts:
            - mountPath: /tmp/gphotos-cdp
              name: chrome-profile
            - mountPath: /home/nonroot/Downloads/gphotos-cdp
              name: google-photos
          volumes:
          - name: chrome-profile
            hostPath:
              path: /mnt/locke-nas/iago-home/gphotos-cdp
              type: Directory
          - name: google-photos
            hostPath:
              path: /mnt/locke-nas/google-photos
              type: Directory
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gphotos-sync-long
  namespace: gphotos-sync
spec:
  schedule: "0 0 1 */1 *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          hostPID: true
          containers:
          - name: gphotos-sync
            image: ghcr.io/iaguis/gphotos-cdp:v1
            imagePullPolicy: Always
            command:
            - /usr/bin/gphotos-sync.sh
            - long
            env:
            - name: HEALTHCHECK_ID
              valueFrom:
                secretKeyRef:
                  name: gphotos-sync-long-healthcheck
                  key: id
            volumeMounts:
            - mountPath: /tmp/gphotos-cdp
              name: chrome-profile
            - mountPath: /home/nonroot/Downloads/gphotos-cdp
              name: google-photos
          volumes:
          - name: chrome-profile
            hostPath:
              path: /mnt/locke-nas/iago-home/gphotos-cdp
              type: Directory
          - name: google-photos
            hostPath:
              path: /mnt/locke-nas/google-photos
              type: Directory
          restartPolicy: Never
